### ISSUE TITLE
rename Class "segment"

### ISSUE THREAD

**Issue by Glottotopia** [acoli-repo/ligt#1]
Segment has a very well defined meaning in linguistic theory, namely the phonological segment. However, in the context it is used here, it refers to a portion of a text, which can be of varying size (whole text, paragraph, utterance). In order to avoid confusion, a different term would be good. Maybe "Portion" or "TextUnit"

**Comment by chiarcos** [comment]
Our use of "segment" follows ISO 24612:2012 (https://www.iso.org/standard/37326.html, public description under https://www.cs.vassar.edu/~ide/papers/JNLE-rev.pdf). This must be made clear in the data model in order to avoid confusion.
However, "Portion" or "TextUnit" would be somewhat ideosyncratic. "TextSegment" would be yet another alternative, but this is a reserved term in computing. The closest ISO 24612:2012 term would be "region", but (in theory) segments can be discontinuous whereas regions cannot. We can discuss this further, but at the moment I see no way of renaming "segment" to anything less confusing.
